# Generated by Django 4.0.4 on 2022-04-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_prettynum_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
    ]
