# Generated by Django 4.0.4 on 2022-04-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_remove_userinfo_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettynum',
            name='pretty_user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo', verbose_name='领用人'),
            preserve_default=False,
        ),
    ]
